version: '3'
services:
    openssl:
        build:
            dockerfile: ./dockerfile
            context: .

        image: SSCG/openssl
        container_name: openssl
        volumes:
          - ./data:/data
